version: '3.7'

services:
  n8n:
    image: n8nio/n8n:1.73.1
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_LOG_LEVEL=debug
      - N8N_SECURE_COOKIE=false
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
      - N8N_DIAGNOSTICS_ENABLED=false
    restart: always
